using System.Collections.Generic;

namespace Iv4xr.PluginLib.WorldModel
{
    public class TerminalBlock : Block
    {
        public bool ShowInInventory;
        public bool ShowInTerminal;
        public bool ShowOnHUD;
    }

    public class FunctionalBlock : TerminalBlock
    {
        public bool Enabled;
    }

    public class DoorBase : FunctionalBlock
    {
        public bool Open;
        public bool AnyoneCanUse;
    }

    public class FueledPowerProducer : FunctionalBlock
    {
        public float MaxOutput;
        public float CurrentOutput;
        public float Capacity;
    }

    public static class BlockMapper
    {
        public static readonly Dictionary<string, string> Mapping = new Dictionary<string, string>
        {
            { "DebugSphereLarge", "FunctionalBlock" },
            { "SmallProgrammableBlock", "FunctionalBlock" },
            { "LargeProgrammableBlock", "FunctionalBlock" },
            { "LargeProjector", "FunctionalBlock" },
            { "SmallProjector", "FunctionalBlock" },
            { "LargeBlockConsole", "FunctionalBlock" },
            { "SmallBlockSensor", "FunctionalBlock" },
            { "LargeBlockSensor", "FunctionalBlock" },
            { "SmallBlockSoundBlock", "FunctionalBlock" },
            { "LargeBlockSoundBlock", "FunctionalBlock" },
            { "ButtonPanelLarge", "FunctionalBlock" },
            { "ButtonPanelSmall", "FunctionalBlock" },
            { "LargeSciFiButtonTerminal", "FunctionalBlock" },
            { "LargeSciFiButtonPanel", "FunctionalBlock" },
            { "TimerBlockLarge", "FunctionalBlock" },
            { "TimerBlockSmall", "FunctionalBlock" },
            { "LargeBlockRadioAntenna", "FunctionalBlock" },
            { "SmallBlockRadioAntenna", "FunctionalBlock" },
            { "LargeBlockRadioAntennaDish", "FunctionalBlock" },
            { "LargeBlockBeacon", "FunctionalBlock" },
            { "SmallBlockBeacon", "FunctionalBlock" },
            { "LargeBlockRemoteControl", "TerminalBlock" },
            { "SmallBlockRemoteControl", "TerminalBlock" },
            { "LargeBlockLaserAntenna", "FunctionalBlock" },
            { "SmallBlockLaserAntenna", "FunctionalBlock" },
            { "LargeBlockCockpit", "TerminalBlock" },
            { "LargeBlockCockpitSeat", "TerminalBlock" },
            { "SmallBlockCockpit", "TerminalBlock" },
            { "DBSmallBlockFighterCockpit", "TerminalBlock" },
            { "CockpitOpen", "TerminalBlock" },
            { "RoverCockpit", "TerminalBlock" },
            { "OpenCockpitSmall", "TerminalBlock" },
            { "OpenCockpitLarge", "TerminalBlock" },
            { "LargeBlockDesk", "TerminalBlock" },
            { "LargeBlockDeskCorner", "TerminalBlock" },
            { "LargeBlockCouch", "TerminalBlock" },
            { "LargeBlockCouchCorner", "TerminalBlock" },
            { "LargeBlockBathroomOpen", "TerminalBlock" },
            { "LargeBlockBathroom", "TerminalBlock" },
            { "LargeBlockToilet", "TerminalBlock" },
            { "SmallBlockCockpitIndustrial", "TerminalBlock" },
            { "LargeBlockCockpitIndustrial", "TerminalBlock" },
            { "PassengerSeatLarge", "TerminalBlock" },
            { "PassengerSeatSmall", "TerminalBlock" },
            { "BuggyCockpit", "TerminalBlock" },
            { "LargeBlockGyro", "FunctionalBlock" },
            { "SmallBlockGyro", "FunctionalBlock" },
            { "LargeBlockBed", "TerminalBlock" },
            { "LargeBlockCryoChamber", "TerminalBlock" },
            { "SmallBlockCryoChamber", "TerminalBlock" },
            { "LargeBlockLockerRoom", "TerminalBlock" },
            { "LargeBlockLockerRoomCorner", "TerminalBlock" },
            { "LargeBlockLockers", "TerminalBlock" },
            { "SmallBlockSmallContainer", "TerminalBlock" },
            { "SmallBlockMediumContainer", "TerminalBlock" },
            { "SmallBlockLargeContainer", "TerminalBlock" },
            { "LargeBlockSmallContainer", "TerminalBlock" },
            { "LargeBlockLargeContainer", "TerminalBlock" },
            { "LargeBlockWeaponRack", "TerminalBlock" },
            { "SmallBlockWeaponRack", "TerminalBlock" },
            { "FoodDispenser", "FunctionalBlock" },
            { "VendingMachine", "FunctionalBlock" },
            { "StoreBlock", "FunctionalBlock" },
            { "AtmBlock", "FunctionalBlock" },
            { "Jukebox", "FunctionalBlock" },
            { "LabEquipment", "FunctionalBlock" },
            { "MedicalStation", "FunctionalBlock" },
            { "TransparentLCDLarge", "FunctionalBlock" },
            { "TransparentLCDSmall", "FunctionalBlock" },
            { "SmallTextPanel", "FunctionalBlock" },
            { "SmallLCDPanelWide", "FunctionalBlock" },
            { "SmallLCDPanel", "FunctionalBlock" },
            { "LargeBlockCorner_LCD_1", "FunctionalBlock" },
            { "LargeBlockCorner_LCD_2", "FunctionalBlock" },
            { "LargeBlockCorner_LCD_Flat_1", "FunctionalBlock" },
            { "LargeBlockCorner_LCD_Flat_2", "FunctionalBlock" },
            { "SmallBlockCorner_LCD_1", "FunctionalBlock" },
            { "SmallBlockCorner_LCD_2", "FunctionalBlock" },
            { "SmallBlockCorner_LCD_Flat_1", "FunctionalBlock" },
            { "SmallBlockCorner_LCD_Flat_2", "FunctionalBlock" },
            { "LargeTextPanel", "FunctionalBlock" },
            { "LargeLCDPanel", "FunctionalBlock" },
            { "LargeLCDPanelWide", "FunctionalBlock" },
            { "LargeLCDPanel5x5", "FunctionalBlock" },
            { "LargeLCDPanel5x3", "FunctionalBlock" },
            { "LargeLCDPanel3x3", "FunctionalBlock" },
            { "RotatingLightLarge", "FunctionalBlock" },
            { "RotatingLightSmall", "FunctionalBlock" },
            { "LargeBlockFrontLight", "FunctionalBlock" },
            { "SmallBlockFrontLight", "FunctionalBlock" },
            { "OffsetSpotlight", "FunctionalBlock" },
            { "SmallDoor", "DoorBase" },
            { "LargeBlockGate", "DoorBase" },
            { "LargeBlockOffsetDoor", "DoorBase" },
            { "SmallSideDoor", "DoorBase" },
            { "LargeBlockSlideDoor", "DoorBase" },
            { "SafeZoneBlock", "FunctionalBlock" },
            { "ContractBlock", "FunctionalBlock" },
            { "LargeBlockBatteryBlock", "FunctionalBlock" },
            { "SmallBlockBatteryBlock", "FunctionalBlock" },
            { "SmallBlockSmallBatteryBlock", "FunctionalBlock" },
            { "SmallBlockSmallGenerator", "FueledPowerProducer" },
            { "SmallBlockLargeGenerator", "FueledPowerProducer" },
            { "LargeBlockSmallGenerator", "FueledPowerProducer" },
            { "LargeBlockLargeGenerator", "FueledPowerProducer" },
            { "LargeHydrogenEngine", "FueledPowerProducer" },
            { "SmallHydrogenEngine", "FueledPowerProducer" },
            { "LargeBlockWindTurbine", "FunctionalBlock" },
            { "LargeBlockSolarPanel", "FunctionalBlock" },
            { "SmallBlockSolarPanel", "FunctionalBlock" },
            { "VirtualMassLarge", "FunctionalBlock" },
            { "VirtualMassSmall", "FunctionalBlock" },
            { "SpaceBallLarge", "FunctionalBlock" },
            { "SpaceBallSmall", "FunctionalBlock" },
            { "SmallLight", "FunctionalBlock" },
            { "SmallBlockSmallLight", "FunctionalBlock" },
            { "LargeBlockLight_1corner", "FunctionalBlock" },
            { "LargeBlockLight_2corner", "FunctionalBlock" },
            { "SmallBlockLight_1corner", "FunctionalBlock" },
            { "SmallBlockLight_2corner", "FunctionalBlock" },
            { "OffsetLight", "FunctionalBlock" },
            { "OxygenTankSmall", "FunctionalBlock" },
            { "LargeHydrogenTank", "FunctionalBlock" },
            { "LargeHydrogenTankSmall", "FunctionalBlock" },
            { "SmallHydrogenTank", "FunctionalBlock" },
            { "SmallHydrogenTankSmall", "FunctionalBlock" },
            { "SmallAirVent", "FunctionalBlock" },
            { "Collector", "FunctionalBlock" },
            { "CollectorSmall", "FunctionalBlock" },
            { "Connector", "FunctionalBlock" },
            { "ConnectorSmall", "FunctionalBlock" },
            { "ConnectorMedium", "FunctionalBlock" },
            { "LargeBlockConveyorSorter", "FunctionalBlock" },
            { "MediumBlockConveyorSorter", "FunctionalBlock" },
            { "SmallBlockConveyorSorter", "FunctionalBlock" },
            { "LargePistonBase", "FunctionalBlock" },
            { "SmallPistonBase", "FunctionalBlock" },
            { "LargeStator", "FunctionalBlock" },
            { "SmallStator", "FunctionalBlock" },
            { "LargeAdvancedStator", "FunctionalBlock" },
            { "SmallAdvancedStator", "FunctionalBlock" },
            { "LargeHinge", "FunctionalBlock" },
            { "MediumHinge", "FunctionalBlock" },
            { "SmallHinge", "FunctionalBlock" },
            { "LargeMedicalRoom", "FunctionalBlock" },
            { "LargeRefinery", "FunctionalBlock" },
            { "Blast Furnace", "FunctionalBlock" },
            { "OxygenGeneratorSmall", "FunctionalBlock" },
            { "LargeAssembler", "FunctionalBlock" },
            { "BasicAssembler", "FunctionalBlock" },
            { "SurvivalKitLarge", "FunctionalBlock" },
            { "SurvivalKit", "FunctionalBlock" },
            { "LargeBlockOxygenFarm", "FunctionalBlock" },
            { "LargeProductivityModule", "FunctionalBlock" },
            { "LargeEffectivenessModule", "FunctionalBlock" },
            { "LargeEnergyModule", "FunctionalBlock" },
            { "SmallExhaustPipe", "FunctionalBlock" },
            { "LargeExhaustPipe", "FunctionalBlock" },
            { "OffroadSuspension3x3", "FunctionalBlock" },
            { "OffroadSuspension5x5", "FunctionalBlock" },
            { "OffroadSuspension1x1", "FunctionalBlock" },
            { "OffroadSmallSuspension3x3", "FunctionalBlock" },
            { "OffroadSmallSuspension5x5", "FunctionalBlock" },
            { "OffroadSmallSuspension1x1", "FunctionalBlock" },
            { "OffroadSuspension3x3mirrored", "FunctionalBlock" },
            { "OffroadSuspension5x5mirrored", "FunctionalBlock" },
            { "OffroadSuspension1x1mirrored", "FunctionalBlock" },
            { "OffroadSmallSuspension3x3mirrored", "FunctionalBlock" },
            { "OffroadSmallSuspension5x5mirrored", "FunctionalBlock" },
            { "OffroadSmallSuspension1x1mirrored", "FunctionalBlock" },
            { "Suspension3x3", "FunctionalBlock" },
            { "Suspension5x5", "FunctionalBlock" },
            { "Suspension1x1", "FunctionalBlock" },
            { "SmallSuspension3x3", "FunctionalBlock" },
            { "SmallSuspension5x5", "FunctionalBlock" },
            { "SmallSuspension1x1", "FunctionalBlock" },
            { "Suspension3x3mirrored", "FunctionalBlock" },
            { "Suspension5x5mirrored", "FunctionalBlock" },
            { "Suspension1x1mirrored", "FunctionalBlock" },
            { "SmallSuspension3x3mirrored", "FunctionalBlock" },
            { "SmallSuspension5x5mirrored", "FunctionalBlock" },
            { "SmallSuspension1x1mirrored", "FunctionalBlock" },
            { "SmallBlockSmallThrustSciFi", "FunctionalBlock" },
            { "SmallBlockLargeThrustSciFi", "FunctionalBlock" },
            { "LargeBlockSmallThrustSciFi", "FunctionalBlock" },
            { "LargeBlockLargeThrustSciFi", "FunctionalBlock" },
            { "LargeBlockLargeAtmosphericThrustSciFi", "FunctionalBlock" },
            { "LargeBlockSmallAtmosphericThrustSciFi", "FunctionalBlock" },
            { "SmallBlockLargeAtmosphericThrustSciFi", "FunctionalBlock" },
            { "SmallBlockSmallAtmosphericThrustSciFi", "FunctionalBlock" },
            { "SmallBlockSmallThrust", "FunctionalBlock" },
            { "SmallBlockLargeThrust", "FunctionalBlock" },
            { "LargeBlockSmallThrust", "FunctionalBlock" },
            { "LargeBlockLargeThrust", "FunctionalBlock" },
            { "LargeBlockLargeHydrogenThrust", "FunctionalBlock" },
            { "LargeBlockSmallHydrogenThrust", "FunctionalBlock" },
            { "SmallBlockLargeHydrogenThrust", "FunctionalBlock" },
            { "SmallBlockSmallHydrogenThrust", "FunctionalBlock" },
            { "LargeBlockLargeAtmosphericThrust", "FunctionalBlock" },
            { "LargeBlockSmallAtmosphericThrust", "FunctionalBlock" },
            { "SmallBlockLargeAtmosphericThrust", "FunctionalBlock" },
            { "SmallBlockSmallAtmosphericThrust", "FunctionalBlock" },
            { "SmallBlockDrill", "FunctionalBlock" },
            { "LargeBlockDrill", "FunctionalBlock" },
            { "LargeShipGrinder", "FunctionalBlock" },
            { "SmallShipGrinder", "FunctionalBlock" },
            { "LargeShipWelder", "FunctionalBlock" },
            { "SmallShipWelder", "FunctionalBlock" },
            { "LargeOreDetector", "FunctionalBlock" },
            { "SmallBlockOreDetector", "FunctionalBlock" },
            { "LargeBlockLandingGear", "FunctionalBlock" },
            { "SmallBlockLandingGear", "FunctionalBlock" },
            { "LargeJumpDrive", "FunctionalBlock" },
            { "SmallCameraBlock", "FunctionalBlock" },
            { "LargeCameraBlock", "FunctionalBlock" },
            { "LargeShipMergeBlock", "FunctionalBlock" },
            { "SmallShipMergeBlock", "FunctionalBlock" },
            { "LgParachute", "DoorBase" },
            { "SmParachute", "DoorBase" },
            { "TargetDummy", "FunctionalBlock" },
            { "LargeWarhead", "TerminalBlock" },
            { "SmallWarhead", "TerminalBlock" },
            { "LargeDecoy", "FunctionalBlock" },
            { "SmallDecoy", "FunctionalBlock" },
            { "SmallGatlingTurret", "FunctionalBlock" },
            { "SmallMissileTurret", "FunctionalBlock" },
            { "LargeInteriorTurret", "FunctionalBlock" },
            { "LargeMissileLauncher", "FunctionalBlock" },
            { "SmallRocketLauncherReload", "FunctionalBlock" }
        };
    }
}
