# Generated by JVMClient, see ClientGenerator.kt
# pylint: disable=C0115,C0116,R0902,C0103,R0903,R0913,W0401,W0622,C0114,R0205,W0614

from typing import List, Dict
from .models import *


class FunctionalBlockAdmin:
    def SetEnabled(self, blockId: str, enabled: bool) -> None:
        pass


class MedicalRoomAdmin:
    def SetHealingAllowed(self, blockId: str, healingAllowed: bool) -> None:
        pass

    def SetRefuelAllowed(self, blockId: str, refuelAllowed: bool) -> None:
        pass

    def SetRespawnAllowed(self, blockId: str, respawnAllowed: bool) -> None:
        pass

    def SetSpawnWithoutOxygenEnabled(
        self, blockId: str, spawnWithoutOxygenEnabled: bool
    ) -> None:
        pass


class PistonBaseAdmin:
    def RecreateTop(self, blockId: str) -> None:
        pass

    def SetVelocity(self, blockId: str, velocity: float) -> None:
        pass


class SensorBlockAdmin:
    def SetFieldMax(self, blockId: str, fieldMax: Vec3F) -> None:
        pass

    def SetFieldMin(self, blockId: str, fieldMin: Vec3F) -> None:
        pass


class TerminalBlockAdmin:
    def SetCustomData(self, blockId: str, customData: str) -> None:
        pass

    def SetCustomName(self, blockId: str, customName: str) -> None:
        pass

    def SetShowInInventory(self, blockId: str, showInInventory: bool) -> None:
        pass

    def SetShowInTerminal(self, blockId: str, showInTerminal: bool) -> None:
        pass

    def SetShowOnHUD(self, blockId: str, showOnHUD: bool) -> None:
        pass


class ThrustAdmin:
    def SetThrustOverride(self, blockId: str, thrustOverride: float) -> None:
        pass


class TimerBlockAdmin:
    def SetTriggerDelay(self, blockId: str, triggerDelay: float) -> None:
        pass

    def Start(self, blockId: str) -> None:
        pass

    def Stop(self, blockId: str) -> None:
        pass

    def TriggerNow(self, blockId: str) -> None:
        pass


class WarheadAdmin:
    def Detonate(self, blockId: str) -> None:
        pass

    def Explode(self, blockId: str) -> None:
        pass

    def SetArmed(self, blockId: str, armed: bool) -> None:
        pass

    def StartCountDown(self, blockId: str) -> bool:
        pass

    def StopCountdown(self) -> bool:
        pass


class BlocksAdmin:
    FunctionalBlock: FunctionalBlockAdmin
    MedicalRoom: MedicalRoomAdmin
    PistonBase: PistonBaseAdmin
    SensorBlock: SensorBlockAdmin
    TerminalBlock: TerminalBlockAdmin
    Thrust: ThrustAdmin
    TimerBlock: TimerBlockAdmin
    Warhead: WarheadAdmin

    def CreateOrUpdateGroup(self, name: str, gridId: str, blockIds: List[str]) -> None:
        pass

    def MapButtonToBlock(
        self, buttonBlockId: str, buttonIndex: int, action: str, targetId: str
    ) -> None:
        pass

    def MapButtonToGroup(
        self, buttonBlockId: str, buttonIndex: int, action: str, groupName: str
    ) -> None:
        pass

    def PlaceAt(
        self,
        blockDefinitionId: DefinitionId,
        position: Vec3F,
        orientationForward: Vec3F,
        orientationUp: Vec3F,
        color: Vec3F,
    ) -> CubeGrid:
        pass

    def PlaceInGrid(
        self,
        blockDefinitionId: DefinitionId,
        gridId: str,
        minPosition: Vec3I,
        orientationForward: Vec3I,
        orientationUp: Vec3I,
        color: Vec3F,
    ) -> str:
        pass

    def Remove(self, blockId: str) -> None:
        pass

    def SetCustomName(self, blockId: str, customName: str) -> None:
        pass

    def SetIntegrity(self, blockId: str, integrity: float) -> None:
        pass


class CharacterAdmin:
    def Create(
        self,
        name: str,
        position: Vec3F,
        orientationForward: Vec3F,
        orientationUp: Vec3F,
    ) -> CharacterObservation:
        pass

    def Die(self) -> None:
        pass

    def LocalCharacterId(self) -> str:
        pass

    def MainCharacterId(self) -> str:
        pass

    def Remove(self, id: str) -> None:
        pass

    def ShowTerminal(self, blockId: str) -> None:
        pass

    def Switch(self, id: str) -> None:
        pass

    def Teleport(
        self, position: Vec3F, orientationForward: Vec3F, orientationUp: Vec3F
    ) -> CharacterObservation:
        pass

    def UpdateEnergy(self, energy: float) -> None:
        pass

    def UpdateHydrogen(self, hydrogen: float) -> None:
        pass

    def UpdateOxygen(self, oxygen: float) -> None:
        pass

    def Use(self, blockId: str, functionIndex: int, action: int) -> None:
        pass


class ObserverAdmin:
    def BlockById(self, blockId: str) -> Block:
        pass

    def GridById(self, gridId: str) -> CubeGrid:
        pass

    def ObserveCharacters(self) -> List[CharacterObservation]:
        pass


class TestAdmin:
    def AdminOnly(self) -> None:
        pass

    def GameOnly(self) -> None:
        pass

    def ObserverOnly(self) -> None:
        pass


class SpaceEngineersAdmin:
    Blocks: BlocksAdmin
    Character: CharacterAdmin
    Observer: ObserverAdmin
    Tests: TestAdmin

    def DebugInfo(self) -> DebugInfo:
        pass

    def Echo(self, text: str) -> str:
        pass

    def Ping(self) -> str:
        pass

    def SetFrameLimitEnabled(self, enabled: bool) -> None:
        pass

    def ShowNotification(self, text: str) -> None:
        pass

    def UpdateDefaultInteractDistance(self, distance: float) -> None:
        pass


class Blocks:
    def Place(self) -> None:
        pass


class Character:
    def BeginUsingTool(self) -> None:
        pass

    def EndUsingTool(self) -> None:
        pass

    def Jump(self, movement: Vec3F) -> None:
        pass

    def MoveAndRotate(
        self, movement: Vec3F, rotation3: Vec2F, roll: float, ticks: int
    ) -> CharacterObservation:
        pass

    def ShowInventory(self) -> None:
        pass

    def ShowTerminal(self) -> None:
        pass

    def SwitchHelmet(self) -> CharacterObservation:
        pass

    def SwitchParkedStatus(self) -> bool:
        pass

    def SwitchWalk(self) -> bool:
        pass

    def TurnOffDampeners(self) -> CharacterObservation:
        pass

    def TurnOffJetpack(self) -> CharacterObservation:
        pass

    def TurnOnDampeners(self) -> CharacterObservation:
        pass

    def TurnOnJetpack(self) -> CharacterObservation:
        pass

    def TurnOnRelativeDampeners(self) -> CharacterObservation:
        pass

    def Use(self) -> None:
        pass


class Debug:
    def CharacterAnimations(self) -> CharacterAnimations:
        pass

    def Particles(self) -> Particles:
        pass

    def Sounds(self) -> SoundBanks:
        pass


class Definitions:
    def AllDefinitions(self) -> List[DefinitionBase]:
        pass

    def BlockDefinitionHierarchy(self) -> Dict[str, str]:
        pass

    def BlockDefinitions(self) -> List[BlockDefinition]:
        pass

    def BlockHierarchy(self) -> Dict[str, str]:
        pass


class Input:
    def StartPlaying(self, snapshots: List[FrameSnapshot]) -> None:
        pass

    def StartRecording(self) -> None:
        pass

    def StopPlaying(self) -> None:
        pass

    def StopRecording(self) -> List[FrameSnapshot]:
        pass


class Items:
    def Activate(self, toolbarLocation: ToolbarLocation) -> None:
        pass

    def Equip(self, toolbarLocation: ToolbarLocation) -> None:
        pass

    def SetToolbarItem(
        self, definitionId: DefinitionId, toolbarLocation: ToolbarLocation
    ) -> None:
        pass

    def Toolbar(self) -> Toolbar:
        pass

    def UnEquipWeapon(self) -> None:
        pass


class Observer:
    def DownloadScreenshotBase64(self) -> str:
        pass

    def NavigationGraph(self, gridId: str) -> NavGraph:
        pass

    def Observe(self) -> CharacterObservation:
        pass

    def ObserveBlocks(self) -> Observation:
        pass

    def ObserveCharacters(self) -> List[CharacterObservation]:
        pass

    def ObserveControlledEntity(self) -> ExtendedEntity:
        pass

    def ObserveFloatingObjects(self) -> List[FloatingObject]:
        pass

    def ObserveNewBlocks(self) -> Observation:
        pass

    def SwitchCamera(self) -> None:
        pass

    def TakeScreenshot(self, absolutePath: str) -> None:
        pass


class FocusedScreen:
    def CloseScreen(self) -> None:
        pass

    def CloseScreenNow(self) -> None:
        pass

    def Data(self) -> object:
        pass


class GamePlay:
    def Data(self) -> GamePlayData:
        pass

    def ShowMainMenu(self) -> None:
        pass

    def ShowToolbarConfig(self) -> None:
        pass


class JoinGame:
    def Close(self) -> None:
        pass

    def Data(self) -> JoinGameData:
        pass

    def DirectConnect(self) -> None:
        pass

    def JoinWorld(self) -> None:
        pass

    def Refresh(self) -> None:
        pass

    def SelectGame(self, index: int) -> None:
        pass

    def SelectTab(self, index: int) -> None:
        pass

    def ServerDetails(self) -> None:
        pass


class LoadGame:
    def Close(self) -> None:
        pass

    def Data(self) -> LoadGameData:
        pass

    def Delete(self) -> None:
        pass

    def DoubleClickWorld(self, index: int) -> None:
        pass

    def Edit(self) -> None:
        pass

    def Filter(self, text: str) -> None:
        pass

    def Load(self) -> None:
        pass

    def Publish(self) -> None:
        pass

    def Save(self) -> None:
        pass


class Loading:
    def Data(self) -> LoadingData:
        pass


class MainMenu:
    def Character(self) -> None:
        pass

    def Continue(self) -> None:
        pass

    def Data(self) -> MainMenuData:
        pass

    def ExitToMainMenu(self) -> None:
        pass

    def ExitToWindows(self) -> None:
        pass

    def JoinGame(self) -> None:
        pass

    def LoadGame(self) -> None:
        pass

    def NewGame(self) -> None:
        pass

    def Options(self) -> None:
        pass

    def Save(self) -> None:
        pass

    def SaveAs(self) -> None:
        pass


class Medicals:
    def Data(self) -> MedicalsData:
        pass

    def Join(self) -> None:
        pass

    def Refresh(self) -> None:
        pass

    def Respawn(self) -> None:
        pass

    def SelectFaction(self, factionIndex: int) -> None:
        pass

    def SelectRespawn(self, roomIndex: int) -> None:
        pass

    def ShowMessageOfTheDay(self) -> None:
        pass


class MessageBox:
    def Data(self) -> MessageBoxData:
        pass

    def PressNo(self) -> None:
        pass

    def PressYes(self) -> None:
        pass


class NewGame:
    def Close(self) -> None:
        pass


class SaveAs:
    def Data(self) -> SaveAsData:
        pass

    def PressCancel(self) -> None:
        pass

    def PressOk(self) -> None:
        pass

    def SetName(self, name: str) -> None:
        pass


class ServerConnect:
    def Close(self) -> None:
        pass

    def Connect(self) -> None:
        pass

    def Data(self) -> ServerConnectData:
        pass

    def EnterAddress(self, address: str) -> None:
        pass

    def ToggleAddServerToFavorites(self) -> None:
        pass


class CommsTab:
    pass


class ControlPanelTab:
    def Data(self) -> TerminalControlPanelData:
        pass

    def EnterBlockGroup(self, text: str) -> None:
        pass

    def FilterBlocks(self, text: str) -> None:
        pass

    def GroupDelete(self) -> None:
        pass

    def GroupSave(self) -> None:
        pass


class FactionsTab:
    pass


class GpsTab:
    pass


class InfoTab:
    def ConvertToShip(self) -> None:
        pass

    def ConvertToStation(self) -> None:
        pass

    def Data(self) -> TerminalInfoData:
        pass

    def EnterGridName(self, name: str) -> None:
        pass

    def RenameGrid(self) -> None:
        pass

    def SetEnemyAntennaRange(self, value: float) -> None:
        pass

    def SetFriendlyAntennaRange(self, value: float) -> None:
        pass

    def SetOwnedAntennaRange(self, value: float) -> None:
        pass

    def SetShowAntennaRangeEnabled(self, enabled: bool) -> None:
        pass

    def SetShowCenterOfMassEnabled(self, enabled: bool) -> None:
        pass

    def SetShowGravityRangeEnabled(self, enabled: bool) -> None:
        pass

    def SetShowGridPivotEnabled(self, enabled: bool) -> None:
        pass

    def SetShowSensorsFieldRangeEnabled(self, enabled: bool) -> None:
        pass


class InventorySide:
    def ClickSelectedItem(self) -> None:
        pass

    def DoubleClickSelectedItem(self) -> None:
        pass

    def Filter(self, text: str) -> None:
        pass

    def FilterAll(self) -> None:
        pass

    def FilterEnergy(self) -> None:
        pass

    def FilterShip(self) -> None:
        pass

    def FilterStorage(self) -> None:
        pass

    def FilterSystem(self) -> None:
        pass

    def SelectItem(self, index: int) -> None:
        pass

    def SwapToCharacterOrItem(self) -> None:
        pass

    def SwapToGrid(self) -> None:
        pass

    def ToggleHideEmpty(self) -> None:
        pass


class InventoryTab:
    Left: InventorySide
    Right: InventorySide

    def Data(self) -> TerminalInventoryData:
        pass

    def Deposit(self) -> None:
        pass

    def DropSelected(self) -> None:
        pass

    def FromBuildPlannerToProductionQueue(self) -> None:
        pass

    def SelectedToProductionQueue(self) -> None:
        pass

    def TransferInventoryItemToLeft(
        self, sourceInventoryId: int, destinationInventoryId: int, itemId: int
    ) -> None:
        pass

    def TransferInventoryItemToRight(
        self, sourceInventoryId: int, destinationInventoryId: int, itemId: int
    ) -> None:
        pass

    def Withdraw(self) -> None:
        pass


class ProductionTab:
    def AddToProductionQueue(self, index: int) -> None:
        pass

    def Data(self) -> TerminalProductionData:
        pass

    def EnterBlueprintSearchBox(self, text: str) -> None:
        pass

    def RemoveFromProductionQueue(self, index: int) -> None:
        pass

    def SelectAssembler(self, index: int) -> None:
        pass

    def SelectBlueprint(self, index: int) -> None:
        pass

    def ToggleProductionCooperativeMode(self) -> None:
        pass

    def ToggleProductionRepeatMode(self) -> None:
        pass


class Terminal:
    Comms: CommsTab
    ControlPanel: ControlPanelTab
    Factions: FactionsTab
    Gps: GpsTab
    Info: InfoTab
    Inventory: InventoryTab
    Production: ProductionTab

    def Close(self) -> None:
        pass

    def Data(self) -> TerminalScreenData:
        pass

    def SelectTab(self, index: int) -> None:
        pass


class ToolbarConfig:
    def Close(self) -> None:
        pass

    def Data(self) -> ToolbarConfigData:
        pass

    def DropGridItemToToolbar(self, gridLocation: int, toolbarLocation: int) -> None:
        pass

    def Search(self, text: str) -> None:
        pass

    def SelectCategory(self, index: int) -> None:
        pass


class Screens:
    FocusedScreen: FocusedScreen
    GamePlay: GamePlay
    JoinGame: JoinGame
    LoadGame: LoadGame
    Loading: Loading
    MainMenu: MainMenu
    Medicals: Medicals
    MessageBox: MessageBox
    NewGame: NewGame
    SaveAs: SaveAs
    ServerConnect: ServerConnect
    Terminal: Terminal
    ToolbarConfig: ToolbarConfig

    def WaitUntilTheGameLoaded(self) -> None:
        pass


class Session:
    def Connect(self, address: str) -> None:
        pass

    def Disconnect(self) -> None:
        pass

    def ExitGame(self) -> None:
        pass

    def ExitToMainMenu(self) -> None:
        pass

    def Info(self) -> object:
        pass

    def LoadScenario(self, scenarioPath: str) -> None:
        pass


class SpaceEngineers:
    Admin: SpaceEngineersAdmin
    Blocks: Blocks
    Character: Character
    Debug: Debug
    Definitions: Definitions
    Input: Input
    Items: Items
    Observer: Observer
    Screens: Screens
    Session: Session

    def Close(self) -> None:
        pass
