# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: 
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  jvmTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Change wrapper permissions
        run: chmod +x JvmClient/gradlew

      # Runs a set of commands using the runners shell
      - name: Unit tests
        run: |
          echo Running JVM unit tests
          cd JvmClient/
          ./gradlew :cleanJvmTest :jvmTest --tests "spaceEngineers.game.mockable.*"  --tests "spaceEngineers.model.*"
  csTest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: |
          echo Running Cs unit tests
          cd Source/Tests/Ivxr.PlugIndependentLib.Tests
          dotnet test
