name: CI Tests

on: 
  push:
  pull_request:
  workflow_dispatch:


jobs:
  jvmTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Change wrapper permissions
        run: chmod +x JvmClient/gradlew

      - name: Unit tests
        run: |
          echo Running JVM unit tests
          cd JvmClient/
          ./gradlew :cleanJvmTest :jvmTest --tests "spaceEngineers.game.mockable.*"  --tests "spaceEngineers.model.*"

      - name: Upload coverage to Codecov
        run: |
          echo Uploading coverage
          cd JvmClient/
          ./gradlew jacocoTestReport
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -f build/reports/jacoco/test/jacocoTestReport.xml
  ktLint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Change wrapper permissions
        run: chmod +x JvmClient/gradlew
      - name: Ktlint
        run: |
          echo Checking code style
          cd JvmClient/
          ./gradlew ktCheck
          
  csTest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: |
          echo Running Cs unit tests
          cd Source/Tests/Ivxr.PlugIndependentLib.Tests
          dotnet test
